### ISSUE TITLE
LOG Consistency:Display the pinning policy options same as block cache options / metadata cache options

### ISSUE THREAD

**Issue by udi-speedb** [speedb-io/speedb#804]
block cache is displayed like this:
```
  block_cache_options:
    capacity : 33554432
    num_shard_bits : 6
    strict_capacity_limit : 0
    memory_allocator : None
    high_pri_pool_ratio: 0.000
    low_pri_pool_ratio: 0.000
```
metadata cache options like this:
```
  metadata_cache_options:
    top_level_index_pinning: 0
    partition_pinning: 0
    unpartitioned_pinning: 0
```
Whereas, pinning policy options differently:
```
  pinning_policy_options:
    pinning_policy.capacity: 26843545
    pinning_policy.last_level_with_data_percent: 10
    pinning_policy.mid_percent: 70
```
This issue will just remove the "pinning_policy." prefix.
